######################################################################
# Automatically generated by qmake (2.01a) Fri Jan 11 21:37:52 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT -= gui
QT += network

# Input
HEADERS += EFtpClient.hpp EFtpMonitor.hpp EFtpMonitorInotify.hpp
SOURCES += cli.cpp EFtpClient.cpp EFtpMonitor.cpp EFtpMonitorInotify.cpp
